on:
  push:
    # Sequence of patterns matched against refs/tags
  pull_request:
  workflow_dispatch:

name: Build and upload artifact

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files mkdocs-material
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy

  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add git
            sh .git-hook
            apk add make
            make -j (nproc)

      - name: make zip
        run: ./package.py
      - uses: actions/upload-artifact@v2
        with:
          name: Pdfs
          path: pdfs/*.pdf

      # NB: At this point we have not yet run semantic-release, so we don't have a tag
      # thus eine/tip will *never* create a release
      # (which is now handled by semantic-release)

      - name: Upload latest files to latest
        uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: pdfs/*.pdf
          tag: latest

      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
      - run: yarn install
      - name: Semantic Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

