on:
  push:
    # Sequence of patterns matched against refs/tags
  pull_request:
  workflow_dispatch:

name: Build and upload artifact

jobs:
 build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add git
            sh .git-hook
            apk add make
            make
      - uses: actions/upload-artifact@v2
        with:
          name: pdfs.zip
          path: pdfs.zip
