on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    tags:
    - 'v*'
  workflow_dispatch:

name: Build, Release and Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt install texlive texlive-metapost texlive-lang-english texlive-lang-european texlive-latex-extra texlive-luatex gregorio latexmk
          
      - name: Latex
        run: |
          sh .git-hook
          cd compline
          env openout_any=a latexmk --shell-escape --pdflatex=lualatex --pdf compline.tex
          cd ../

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload pdf
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: compline/compline.pdf
          asset_name: compline.pdf
          asset_content_type: application/pdf
